<?php

if (isset($_POST["register"])) {
    header("location: index.php?route=register");
    exit();
}

?>

<main>
    <h1 class="test" id="tcg_h1"> choisissez votre TCG </h1>
    <form method="post" id="tcg_choice">
        <button type="submit" name="md" id="md" class="tcg">
            <p id="tcg_name"> Master Duel </p>
        </button>
        <button type="submit" name="rd" id="rd" class="tcg">
            <p id="tcg_name"> Rush Duel </p>
        </button>
        <button type="submit" name="cfv" id="cfv" class="tcg">
            <p id="tcg_name"> Cardfight Vanguard </p>
        </button>
    </form>
</main>