<?php

if (isset($_POST["register"])) {
    header("location: index.php?route=register");
    exit();
}

?>

<main>
    <h1 class="test"> choisissez votre TCG </h1>
    <form method="post">
        <button type="submit" name="md">
            Master Duel
        </button>
        <button type="submit" name="rd">
            Rush Duel
        </button>
        <button type="submit" name="cfv">
            Cardfight Vanguard
        </button>
    </form>
</main>