<?php

if (isset($_POST["register"])) {
    header("location: index.php?route=register");
    exit();
}

?>

<main>
    <h1 class="test" id="tcg_h1"> choisissez votre TCG </h1>
    <div id="tcg_choice">
        <div id="md" class="tcg">
            <a href="index.php/md" class="tcg_name">
                <img src="assets/images/ygo_logo.png" alt="">
            </a>
        </div>
        <div id="rd" class="tcg">
            <a href="index.php/rush" class="tcg_name">
                <img src="assets/images/rush_logo.png" alt="">
            </a>
        </div>
        <div id="cfv" class="tcg">
            <a href="index.php/vanguard" class="tcg_name">
                <img src="assets/images/vanguard_logo.webp" alt="">
            </a>
        </div>
    </div>
</main>