<?php

$dossier = "assets/images/pics/";
$images = glob($dossier . "*.{png}", GLOB_BRACE);
$id_card = array_rand($images);
$card_way = $images[$id_card];

?>

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="assets/styles/css/style.css">
    <title>project-name</title>
</head>
<body>
    <header>
        <nav>
            <input type="checkbox" id="menu-toggle">
            <label for="menu-toggle" class="burger">
                <span></span>
                <span></span>
                <span></span>
            </label>
            <ul id="menu-side">
                <li><a href="index.php?route=home" id="accueil">Accueil</a></li>
                <li><a href="index.php?route=register" id="register">S'inscrire</a></li>
                <li><a href="index.php?route=login" id="login">Se connecter</a></li>
            </ul>
        </nav>
    </header>
    <div id="background">
        <div class="card">
            <img class="face" src="<?=$card_way?>" alt="">
            <img class="back" src="assets/images/backcard.jpg" alt="">
        </div>
    </div>
    <?php
        if (isset($route)) {
            require "templates/$route.phtml";
        } else {
            require "templates/notFound.phtml";
        }
    ?>
    <script>
        const banqueImages = <?php
            echo json_encode($images);
        ?>;
        console.log("CardList :", banqueImages);
    </script>
    <script src="assets/styles/js/fall.js"></script>
</body>
</html>