<?php

$id_card = random_int(1, 4);

?>

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="assets/styles/css/style.css">
    <title>project-name</title>
</head>
<body>
    <header>
        <nav>
            <input type="checkbox" id="menu-toggle">
            <label for="menu-toggle" class="burger">
                <span></span>
                <span></span>
                <span></span>
            </label>
            <ul id="menu-side">
                <li><a href="index.php?route=home" id="accueil">Accueil</a></li>
                <li><a href="index.php?route=register" id="register">S'inscrire</a></li>
                <li><a href="index.php?route=login" id="login">Se connecter</a></li>
            </ul>
        </nav>
    </header>
    <div id="background">
        <div class="card">
            <img class="face" src="assets/images/<?=$id_card?>.png" alt="">
            <img class="back" src="assets/images/backcard.jpg" alt="">
        </div>
    </div>
    <?php
        if (isset($route)) {
            require "templates/$route.phtml";
        } else {
            require "templates/notFound.phtml";
        }
    ?>
</body>
</html>