<?php

$chemin_serveur = __DIR__ . "/../";

$dossier = [
    ["assets/images/CFVpics/",   "assets/images/CFback.png"],
    ["assets/images/YGORDpics/", "assets/images/RDback.png"],
    ["assets/images/YGOMDpics/", "assets/images/MDback.png"]
];

$tcg_id = $dossier[array_rand($dossier)];
$tcg_cards = $tcg_id[0];
$tcg_back = $tcg_id[1];

$chemin_recherche = $chemin_serveur . $tcg_cards . "*.{png,webp,WEBP,jpg,jpeg}";
$chemin_recherche = str_replace('\\', '/', $chemin_recherche);

$cardlist = glob($chemin_recherche, GLOB_BRACE);
$randcard = $cardlist[array_rand($cardlist)];
$idcardonly = basename($randcard);
$idcard = $tcg_cards . $idcardonly;

?>

<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="assets/css/style.css">
    <title>project-name</title>
</head>
<body>
    <header>
        <nav>
            <input type="checkbox" id="menu-toggle">
            <label for="menu-toggle" class="burger">
                <span></span>
                <span></span>
                <span></span>
            </label>
            <ul id="menu-side">
                <li><a href="index.php/home" id="accueil">Accueil</a></li>
                <li><a href="index.php/register" id="register">S'inscrire</a></li>
                <li><a href="index.php/login" id="login">Se connecter</a></li>
            </ul>
        </nav>
    </header>
    <div id="background">
        <div class="card">
            <img class="face" src="<?= $idcard ?>" alt="">
            <img class="back" src="<?= $tcg_back ?>" alt="">
        </div>
    </div>
    <?php
        if (isset($route)) {
            require "templates/$route.phtml";
        } else {
            require "templates/notFound.phtml";
        }
    ?>
    <script src="assets/styles/js/fall.js"></script>
</body>
</html>