<main>
    <form method="post">
        <div>
            <label for="username">Nom :</label>
            <input type="text" id="username" name="username">
        </div>
        <div>
            <label for="password">Mot de Passe :</label>
            <input type="password" id="password" name="password">
        </div>
        <button type="submit">
            Se connecter
        </button>
    </form>
</main>